# Generated by Django 4.2.4 on 2023-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.ImageField(default='default_cower_picture.png', upload_to='books/image'),
        ),
    ]
